google.maps.__gjsload__('infowindow', function(_){var Uya=function(){this.h=new _.x.Set},Vya=function(a,b){if(1===a.h.size){var c=_.u(Array,"from").call(Array,_.u(a.h,"values").call(a.h))[0];c.Ek!==b.Ek&&(c.set("map",null),a.h.delete(c))}a.h.add(b)},HF=function(a){var b=this;this.N=a.qv;this.o=null;this.O=a.shouldFocus;this.h=_.Hm("div");_.Tu(this.h,"default");this.h.style.position="absolute";this.h.style.left=this.h.style.top="0";a.gh.floatPane.appendChild(this.h);this.H=_.Hm("div",this.h);this.D=_.Hm("div",this.H);this.j=_.Hm("div",this.D);this.j.setAttribute("role",
"dialog");this.j.tabIndex=-1;this.l=_.Hm("div",this.j);_.fsa(this.h);_.em(this.j,"gm-style-iw");_.em(this.H,"gm-style-iw-a");_.em(this.D,"gm-style-iw-t");_.em(this.j,"gm-style-iw-c");_.em(this.l,"gm-style-iw-d");_.Ii.h&&(a.sc?this.j.style.paddingLeft=0:this.j.style.paddingRight=0,this.j.style.paddingBottom=0,this.l.style.overflow="scroll");GF(this,!1);_.F.Wa(this.h,"mousedown",_.cf);_.F.Wa(this.h,"mouseup",_.cf);_.F.Wa(this.h,"mousemove",_.cf);_.F.Wa(this.h,"pointerdown",_.cf);_.F.Wa(this.h,"pointerup",
_.cf);_.F.Wa(this.h,"pointermove",_.cf);_.F.Wa(this.h,"dblclick",_.cf);_.F.Wa(this.h,"click",_.cf);_.F.Wa(this.h,"touchstart",_.cf);_.F.Wa(this.h,"touchend",_.cf);_.F.Wa(this.h,"touchmove",_.cf);_.F.Vb(this.h,"contextmenu",this,this.vx);_.F.Vb(this.h,"wheel",this,_.cf);_.F.Vb(this.h,"mousewheel",this,_.$e);_.F.Vb(this.h,"MozMousePixelScroll",this,_.$e);this.J=new _.HB({pi:new _.I(8,8),Wg:new _.ig(14,14),offset:new _.I(-6,-6)});this.j.appendChild(this.J.element);_.F.Wa(this.J.element,"click",function(c){_.cf(c);
_.F.trigger(b,"closeclick");b.set("open",!1)});this.m=null;this.F=this.K=!1;this.C=new _.Th(function(){!b.K&&b.get("content")&&b.get("visible")&&(_.F.trigger(b,"domready"),b.K=!0)},0);this.M=_.F.Wa(this.h,"keydown",function(c){"Escape"!==c.key&&"Esc"!==c.key||!b.j.contains(document.activeElement)||(c.stopPropagation(),_.F.trigger(b,"closeclick"),b.set("open",!1))})},Wya=function(a){var b=!!a.get("open"),c=a.get("content");c=b?c:null;if(c==a.m)GF(a,b&&a.get("position"));else{if(a.m){var d=a.m.parentNode;
d==a.l&&d.removeChild(a.m)}c&&(a.K=!1,a.l.appendChild(c));GF(a,b&&a.get("position"));a.m=c;IF(a)}},Xya=function(a){var b=a.get("pixelOffset")||new _.ig(0,0),c=new _.ig(a.j.offsetWidth,a.j.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;0>b.height&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},GF=function(a,b){a.h.style.visibility=b?"":"hidden";b&&a.O&&(a.focus(),a.O=!1);b?Yya(a):a.F=!1},IF=function(a){var b=a.get("layoutPixelBounds"),
c=a.get("pixelOffset");var d=a.get("maxWidth")||648;var e=a.get("minWidth")||0;c?(b?(c=b.Ha-b.Ca-(11+-c.height),b=b.Na-b.Ea-6,240<=b&&(b-=120),240<=c&&(c-=120)):(b=648,c=654),b=Math.min(b,d),b=Math.max(e,b),b=Math.max(0,b),c=Math.max(0,c),d={Hf:new _.ig(b,c),minWidth:e}):d=null;if(e=d)d=e.Hf,e=e.minWidth,a.j.style.maxWidth=_.Nl(d.width),a.j.style.maxHeight=_.Nl(d.height),a.j.style.minWidth=_.Nl(e),a.l.style.maxHeight=_.Ii.h?_.Nl(d.height-18):_.Nl(d.height-36),JF(a),a.C.start()},Yya=function(a){!a.F&&
a.get("open")&&a.get("visible")&&a.get("position")&&(_.F.trigger(a,"visible"),a.F=!0)},JF=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=Xya(a),d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;c=b.y+c.bottom;_.Gm(a.H,b);b=a.get("zIndex");_.Im(a.h,_.he(b)?b:e+60);a.set("pixelBounds",_.Wh(d,e,f,c))}},Zya=function(a,b){var c=a.__gm;a=c.get("panes");c=c.get("innerContainer");b={gh:a,sc:_.rs.sc(),qv:c,shouldFocus:b};return new HF(b)},KF=function(a,b,c){var d=this;this.o=!0;this.Ya=this.m=
this.l=null;var e=b.__gm,f=b instanceof _.qf;f&&c?c.then(function(m){d.o&&(d.l=m,d.Ya=new _.IB(function(p){d.m=new _.Pn(b,m,p,function(){});m.nb(d.m);return d.m}),d.Ya.bindTo("latLngPosition",a,"position"),k.bindTo("position",d.Ya,"pixelPosition"))}):(this.Ya=new _.IB,this.Ya.bindTo("latLngPosition",a,"position"),this.Ya.bindTo("center",e,"projectionCenterQ"),this.Ya.bindTo("zoom",e),this.Ya.bindTo("offset",e),this.Ya.bindTo("projection",b),this.Ya.bindTo("focus",b,"position"));this.D=f?a.wg()?"Ia":
"Id":null;this.F=f?a.wg()?148284:148285:null;this.h=[];var g=new _.JB(["scale"],"visible",function(m){return null==m||.3<=m});this.Ya&&g.bindTo("scale",this.Ya);var h=a.get("shouldFocus"),k=this.C=Zya(b,h);k.set("logAsInternal",a.wg());k.bindTo("ariaLabel",a);k.bindTo("zIndex",a);k.bindTo("layoutPixelBounds",e,"pixelBounds");k.bindTo("disableAutoPan",a);k.bindTo("pendingFocus",a);k.bindTo("maxWidth",a);k.bindTo("minWidth",a);k.bindTo("content",a);k.bindTo("pixelOffset",a);k.bindTo("visible",g);this.Ya&&
k.bindTo("position",this.Ya,"pixelPosition");this.j=new _.Th(function(){if(b instanceof _.qf)if(d.l){var m=a.get("position");m&&_.Xha(b,d.l,new _.If(m),Xya(k))}else c.then(function(){return d.j.start()});else(m=k.get("pixelBounds"))?_.F.trigger(e,"pantobounds",m):d.j.start()},150);if(f){var l=null;this.h.push(_.F.Ub(a,"position_changed",function(){var m=a.get("position");!m||a.get("disableAutoPan")||m.equals(l)||(d.j.start(),l=m)}))}else a.get("disableAutoPan")||this.j.start();k.set("open",!0);this.h.push(_.F.addListener(k,
"domready",function(){a.trigger("domready")}));this.h.push(_.F.addListener(k,"visible",function(){a.trigger("visible")}));this.h.push(_.F.addListener(k,"closeclick",function(){a.close();a.trigger("closeclick")}));this.D&&_.og(b,this.D);this.F&&_.cg(b,this.F)},$ya=function(a,b,c){return b instanceof _.qf?new KF(a,b,c):new KF(a,b)},aza=function(a){a=a.__gm;return a.IW_AUTO_CLOSER=a.IW_AUTO_CLOSER||new Uya};_.B(HF,_.G);_.n=HF.prototype;_.n.ariaLabel_changed=function(){var a=this.get("ariaLabel");a?this.j.setAttribute("aria-label",a):this.j.removeAttribute("aria-label")};_.n.open_changed=function(){Wya(this)};_.n.content_changed=function(){Wya(this)};
_.n.pendingFocus_changed=function(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?_.Yu(this.j,!0):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))};
_.n.dispose=function(){var a=this;setTimeout(function(){document.activeElement&&document.activeElement!==document.body||(a.o&&a.o!==document.body?_.Yu(a.o,!0)||_.Yu(a.N,!0):_.Yu(a.N,!0))});this.M&&_.F.removeListener(this.M);this.h.parentNode.removeChild(this.h);this.C.stop();this.C.dispose()};_.n.pixelOffset_changed=function(){var a=this.get("pixelOffset")||new _.ig(0,0);this.D.style.right=_.Nl(-a.width);this.D.style.bottom=_.Nl(-a.height+11);IF(this)};_.n.layoutPixelBounds_changed=function(){IF(this)};
_.n.position_changed=function(){this.get("position")?(JF(this),GF(this,!!this.get("open"))):GF(this,!1)};_.n.zIndex_changed=function(){JF(this)};_.n.visible_changed=function(){_.Qu(this.h,this.get("visible"));this.C.start();this.get("visible")?Yya(this):this.F=!1};_.n.vx=function(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d==c,d=d.parentNode;b?_.$e(a):_.bf(a)};
_.n.focus=function(){this.o=document.activeElement;var a;_.Ii.F&&(a=this.l.getBoundingClientRect());if(this.get("disableAutoPan"))_.Yu(this.j,!0);else{var b=_.Pla(this.l);if(b.length){b=b[0];a=a||this.l.getBoundingClientRect();var c=b.getBoundingClientRect();_.Yu(c.bottom<=a.bottom&&c.right<=a.right?b:this.j,!0)}else _.Yu(this.J.element,!0)}};KF.prototype.close=function(){if(this.o){this.o=!1;for(var a=_.A(this.h),b=a.next();!b.done;b=a.next())_.F.removeListener(b.value);this.h.length=0;this.j.stop();this.j.dispose();this.l&&this.m&&this.l.$f(this.m);a=this.C;a.unbindAll();a.set("open",!1);a.dispose();this.Ya&&this.Ya.unbindAll()}};_.Ze("infowindow",{gu:function(a){var b=null;_.F.Ub(a,"map_changed",function d(){var e=a.get("map");b&&(b.Ip.h.delete(a),b.Ox.close(),b=null);if(e){var f=e.__gm;f.get("panes")?(b={Ox:$ya(a,e,e instanceof _.qf?f.h.then(function(g){return g.Pa}):void 0),Ip:aza(e)},Vya(b.Ip,a)):_.F.addListenerOnce(f,"panes_changed",d)}})}});});
